config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :posts
  resources :sessions
  

  root :to => redirect('/posts')

  get 'signup' => 'users#new', as: :signup
  get 'logout' => 'sessions#destroy', as: :logout
  get 'login' => 'sessions#new', as: :login

end

app/models/ability.rb
class Ability
  include CanCan::Ability

def initialize(user)
    user ||= User.new # guest user (not logged in)
    if User.exists?(user)
      can :manage, :all
      can :create, Post
      can :read, Post

      #look at and update own posts
      can :update, Post do |p|
        p.user_id == user.id
      end
    else # Non-admin user
      can :read, Post
    end
  end

  #def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  #end
end

app/models/post.rb
class Post < ActiveRecord::Base

	#Relationships
	belongs_to :user

	#Validations
	validates_presence_of :title, :description

	#Scopes
	scope :chronological, -> { order(created_at: :asc) }
	scope :reverse_chronological, -> { order(created_at: :desc) }

end

app/models/user.rb
class User < ActiveRecord::Base

	# Use built-in rails support for password protection
  has_secure_password

  #Relationships
  has_many :posts

  #Validations
  validates_presence_of :name, :email
  validates_format_of :email, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+[a-z]{2,})\z/i, message: "is not a valid format"
  validates_presence_of :password, on: :create 
  validates_presence_of :password_confirmation, on: :create 
  validates_confirmation_of :password, message: "does not match"
  validates_length_of :password, minimum: 4, message: "must be at least 4 characters long", allow_blank: true

# login by email address
  def self.authenticate(email, password)
    find_by_email(email).try(:authenticate, password)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "You are not authorized to take this action"
    redirect_to home_path
  end

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def logged_in?
    current_user
  end
  helper_method :logged_in?

  def check_login
    redirect_to login_url, alert: "You need to log in to view this page." if current_user.nil?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.reverse_chronological
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    post_count = @post.click_count + 1
    @post.update_attribute(:click_count, post_count)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :title, :description, :created_at)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to login_path, notice: 'Thank you for creating an account on JobApp! Log in to post new jobs.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Your account was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<div class="top-bar">
	<div class="large-1 column">
		<div class="top-bar-left">
			<ul class="menu">
				<div id="app_title">
					<li id="nav-link">
						<%= link_to "JobApp", posts_path %>
					</li>
				</div>
			</ul>
		</div>
	</div>
	<div class="small-10 column">
		<div class="top-bar-right">
			<ul class="menu">
				<!-- content once logged in goes here -->
				<% if logged_in? %>
					<li id="nav-link">
						<%= link_to current_user.name, user_path(current_user.id) %>
					</li>
					<li id="nav-link">
						<%= link_to 'Logout', logout_path %>
					</li>
				<% else %>
					<li id="nav-link">
						<%= link_to 'Login', login_path %>
					</li>
					<li id="nav-link">
						<%= link_to 'Sign Up', signup_path %>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>JobApp</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

<%= render :partial => "layouts/nav" %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<h1><legend><%= controller.action_name.capitalize %> Post</legend></h1>
    <%= simple_form_for @post, :html => { :class => 'form-horizontal' } do |f| %>
      <fieldset>

        <%= f.input :title %>
        <%= f.input :description, input_html: { rows: 12 } %>

        <div class="form-actions">
          <%= f.submit nil, :class => 'button radius' %>
          <%= link_to 'Cancel', posts_path, :class => 'button alert radius' %>
        </div>
      </fieldset>
    <% end %>

<% end %>

app/views/posts/_post.html.erb
<div class="post">

  <h2><%= link_to( post.title, post, :target => '_blank' ) %></h2>
  <h6>Posted on <%= post.created_at.strftime("%A, %B %-d, %Y") %> by <%= post.user.name %></h6>
  <p><%= simple_format(post.description) %></p>
<br></br>

</div>

app/views/posts/edit.html.erb
<div class="row">
  <div class="large-6 column">
	<%= render 'form' %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="row">
    <div class="large-10 column">
        <p id="notice"><%= notice %></p>
        <h1>Available Jobs</h1>
        <% if logged_in? %>
          <%= link_to "Post a New Job", new_post_path, :class => 'button radius' %>
        <% else %>
          <p>Please <%= link_to "log in", login_path %> or <%= link_to "sign up", signup_path %> to post new jobs on this board.</p>
        <% end %>
        <br></br>
        <% @posts.each do |post| %>
          <%= render post %>
        <% end %>
    </div>
</div>

<br></br>

<br>

app/views/posts/new.html.erb
<div class="row">
  <div class="large-10 column">
	<%= render 'form' %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="small-12 column">

	<div class="row">
		<p id="notice"><%= notice %></p>
	</div>

	<div class="row">
		<br></br>
		<h5><%= link_to '< Back to Job Board', posts_path %></h5>
	</div>

	<div class="row">
		<p>
			<h2><%= @post.title %></h2>
		</p>
	</div>

	<div class="row">
		<p>
			<h6>Posted on <%= @post.created_at.strftime("%A, %B %-d, %Y") %> by <%= @post.user.name %></h6>
		</p>
	</div>

	<div class="row">
		<p>
			<%= @post.description %>
		</p>
	</div>

	<div class="row">
		<% if @post.click_count == 1 %>
		<p>This post has been clicked on 1 time.</p> 
		<% else %> 
		<p>This post has been clicked on <strong><%= @post.click_count %></strong> times.</p>
		<% end %>
	</div>

	<br></br>
	<div class="row">
		<% if logged_in? && current_user.id == @post.user_id %>
		<%= link_to 'Edit', edit_post_path(@post), :class => 'button radius' %>
		<%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'button alert radius' %>
		<% end %>
	</div>

</div>

app/views/users/_form.html.erb
<div class="row">
  <div class="large-4 column">

<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

    <% if controller.action_name == "new" %>
      <h1><legend>Sign Up</legend></h1>
    <% else %>
      <h1><legend>Edit Account</legend></h1>
    <% end %>
      <%= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
      <fieldset>

        <%= f.input :name %>
        <%= f.input :email %>

        <%= f.input :password %>
        <%= f.input :password_confirmation %>

        <div class="form-actions">
        <% if controller.action_name == "new" %>
          <%= f.submit 'Sign Up', :class => 'button radius' %>
          <%= link_to 'Cancel', posts_path, :class => 'button alert radius' %>
        <% else %>
          <%= f.submit 'Update Account', :class => 'button radius' %>
          <%= link_to 'Cancel', user_path(current_user.id), :class => 'button alert radius' %>
        <% end %>
        </div>
      </fieldset>   
<% end %>
<% end %>
    </div>
  </div> 

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div class="large-11 column">
<p id="notice"><%= notice %></p>

<h1>Your Account</h1>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit Your Account', edit_user_path(@user), :class => 'button radius' %>

</div>